### ISSUE TITLE
Parsing of currencyExchange failed

### ISSUE THREAD

**Issue by tolik505** [Dhi13man/nordigen_integration#8]
Hi. Thank for the great api integration!

I played with it recently and found one issue while getting account transactons.

`Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>?' in type cast
#0      new TransactionData.fromMap (package:nordigen_integration/data_models/nordigen_transaction_model.dart:55:44)`

Looks like it doesn't expect array of `currencyExchange`. You can try to parse the following transaction:

` {
                "transactionId": "uuid",
                "bookingDate": "2022-08-15",
                "valueDate": "2022-08-15",
                "transactionAmount": {
                    "amount": "-14.54",
                    "currency": "EUR"
                },
                "currencyExchange": [
                    {
                        "sourceCurrency": "USD",
                        "exchangeRate": "0.9771505376",
                        "unitCurrency": "USD",
                        "targetCurrency": "EUR",
                        "quotationDate": "2022-08-15"
                    }
                ],
                "creditorName": "PAYPAL",
                "remittanceInformationUnstructured": "-",
                "remittanceInformationUnstructuredArray": [
                    "-"
                ],
                "additionalInformation": "uuid",
                "bankTransactionCode": "CODE"
            }`

**Comment by Dhi13man** [comment]
Hey, @tolik505! Thanks for bringing this to my attention. As I do not have access to the APIs, it was a bit hard for me to figure out the Data models.

1. As per your sample data, I have raised a PR with changes [here](https://github.com/Dhi13man/nordigen_integration/pull/9). Please check it out and see if it works. 

2. I have also included a Unit Test. Please approve it if it seems alright and feel free to make any required changes.

3. If you have the full model for the potential data that will be returned, we could probably define a more strict `List<CurrencyExchange>` Data Class instead of having `currencyExchange` as a `List<Map<String, dynamic>>`. Please advice.

**Comment by tolik505** [comment]
Hi, Dhiman!
Thanks for such a prompt response!

I've reviewed the PR and it seems that `currencyExchange` should be nullable.
I'm not sure about a strict `List<CurrencyExchange>` since I have only information from the doc and my own transactions data. Thus, I'd keep it more flexible.

**Comment by Dhi13man** [comment]
Changes are up on [pub.dev with version 1.7.5](https://pub.dev/packages/nordigen_integration). Thank you for your time @tolik505. Looking forward to more of your contributions. ;)

**Comment by tolik505** [comment]
Tested, looks good. Thanks a lot Dhiman!
